// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInvoice(arg1, arg2) {
  return window['go']['main']['App']['AddInvoice'](arg1, arg2);
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function GeneratePDF(arg1, arg2) {
  return window['go']['main']['App']['GeneratePDF'](arg1, arg2);
}

export function GeneratePDFFromInvoice(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePDFFromInvoice'](arg1, arg2, arg3);
}

export function GetCompanyPDFSavePath(arg1) {
  return window['go']['main']['App']['GetCompanyPDFSavePath'](arg1);
}

export function GetInvoiceDetail(arg1, arg2) {
  return window['go']['main']['App']['GetInvoiceDetail'](arg1, arg2);
}

export function GetInvoices(arg1) {
  return window['go']['main']['App']['GetInvoices'](arg1);
}

export function IsInvoiceNumberUnique(arg1, arg2) {
  return window['go']['main']['App']['IsInvoiceNumberUnique'](arg1, arg2);
}

export function SaveInvoicePDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveInvoicePDF'](arg1, arg2, arg3);
}

export function SetCompanyPDFSavePath(arg1, arg2) {
  return window['go']['main']['App']['SetCompanyPDFSavePath'](arg1, arg2);
}

export function ToggleInvoicePayment(arg1, arg2) {
  return window['go']['main']['App']['ToggleInvoicePayment'](arg1, arg2);
}

export function UpdateInvoice(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateInvoice'](arg1, arg2, arg3);
}

export function UpdateInvoiceAmounts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateInvoiceAmounts'](arg1, arg2, arg3, arg4);
}
