// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInvoice(arg1) {
  return window['go']['main']['App']['AddInvoice'](arg1);
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function GeneratePDF(arg1) {
  return window['go']['main']['App']['GeneratePDF'](arg1);
}

export function GetInvoices() {
  return window['go']['main']['App']['GetInvoices']();
}

export function ImportTemplate(arg1) {
  return window['go']['main']['App']['ImportTemplate'](arg1);
}
