// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddInvoice(arg1:string,arg2:main.InvoiceInput):Promise<void>;

export function ExportCSV(arg1:string):Promise<string>;

export function GeneratePDF(arg1:string,arg2:string):Promise<string>;

export function GeneratePDFFromInvoice(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetCompanyPDFSavePath(arg1:string):Promise<string>;

export function GetInvoiceDetail(arg1:string,arg2:string):Promise<main.Invoice>;

export function GetInvoices(arg1:string):Promise<Array<main.InvoiceData>>;

export function IsInvoiceNumberUnique(arg1:string,arg2:string):Promise<boolean>;

export function SaveInvoicePDF(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetCompanyPDFSavePath(arg1:string,arg2:string):Promise<string>;

export function ToggleInvoicePayment(arg1:string,arg2:string):Promise<void>;

export function UpdateInvoice(arg1:string,arg2:string,arg3:main.InvoiceInput):Promise<void>;

export function UpdateInvoiceAmounts(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;
