// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddInvoice(arg1:main.Invoice):Promise<void>;

export function ExportCSV():Promise<string>;

export function GeneratePDF(arg1:number):Promise<string>;

export function GetInvoices():Promise<Array<main.Invoice>>;

export function ImportTemplate(arg1:string):Promise<void>;
