name: Build Wails App for macOS

on:
  push:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Go
        run: |
          brew install go
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH  # Ensure Go binaries are in PATH

      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH  # Add Wails to PATH
          export PATH="$(go env GOPATH)/bin:$PATH"  # Apply the change immediately

      - name: Verify Wails Installation
        run: wails doctor  # Check if Wails is working

      - name: Build macOS App
        run: wails build -platform darwin

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-macos
          path: ./build/Invoicer.app
